/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufsm.view;

import br.edu.ufsm.controller.ExtracaoCommit;
import br.edu.ufsm.controller.ExtracaoIssue;
import br.edu.ufsm.controller.ExtracaoRepository;
import br.edu.ufsm.model.Commit;
import br.edu.ufsm.model.Issue;
import br.edu.ufsm.model.Project;
import br.edu.ufsm.persistence.CommitDao;
import br.edu.ufsm.persistence.IssueDao;
import br.edu.ufsm.persistence.IssueLabelDao;
import br.edu.ufsm.persistence.ProjectDao;
import java.util.List;
import org.eclipse.egit.github.core.RepositoryId;
import org.eclipse.egit.github.core.client.GitHubClient;
import org.eclipse.egit.github.core.service.RepositoryService;

/**
 *
 * @author Dougl
 */
public class ExtractView extends javax.swing.JFrame {

    private ProjectDao projectDao;
    private CommitDao commitDao;
    private IssueLabelDao issueLabelDao;
    private GitHubClient client;
    private RepositoryId repo;

    /**
     * Creates new form ExtractView
     */
    public ExtractView() {
        commitDao = new CommitDao();
        projectDao = new ProjectDao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCommit = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnArquivosCommit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnIssue = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnIssueComentarios = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnPullRequest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        inputUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        inputUsuarioProjeto = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        inputNomeProjeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCommit);
        jToolBar1.add(jSeparator3);

        btnArquivosCommit.setText("Arquivos Commit");
        btnArquivosCommit.setFocusable(false);
        btnArquivosCommit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArquivosCommit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArquivosCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquivosCommitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnArquivosCommit);
        jToolBar1.add(jSeparator2);

        btnIssue.setText("Issue");
        btnIssue.setFocusable(false);
        btnIssue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIssue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIssue);
        jToolBar1.add(jSeparator1);

        btnIssueComentarios.setText("Issue Comentários");
        btnIssueComentarios.setFocusable(false);
        btnIssueComentarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIssueComentarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnIssueComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueComentariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnIssueComentarios);
        jToolBar1.add(jSeparator4);

        btnPullRequest.setText("Pull Request");
        btnPullRequest.setFocusable(false);
        btnPullRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPullRequest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPullRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPullRequestActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPullRequest);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autenticação"));

        inputUsuario.setText("douglasgiordano");

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        inputSenha.setText("1995panquecas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputUsuario)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(0, 290, Short.MAX_VALUE))
            .addComponent(inputSenha)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Repositório"));

        jLabel4.setText("Usuário");

        inputUsuarioProjeto.setText("douglasgiordano");

        Nome.setText("Nome");

        inputNomeProjeto.setText("extractgithub");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputUsuarioProjeto)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Nome))
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addComponent(inputNomeProjeto))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUsuarioProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autenticate() {
        client = new GitHubClient();
        client.setCredentials(inputUsuario.getText(), inputSenha.getText());
        RepositoryService service = new RepositoryService();
        repo = new RepositoryId(inputUsuarioProjeto.getText(), inputNomeProjeto.getText());
    }

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        autenticate();
        Project projeto = ExtracaoRepository.extractRepository(client, repo);
        List<Commit> commits = ExtracaoCommit.extract(client, repo);
        projeto.setCommits(commits);
        projectDao = new ProjectDao();
        projectDao.save(projeto);
    }//GEN-LAST:event_btnCommitActionPerformed

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        issueLabelDao = new IssueLabelDao();
        autenticate();
        Project projeto = ExtracaoRepository.extractRepository(client, repo);
        List<Issue> issues = ExtracaoIssue.extract(client, repo);
        projeto.setIssue(issues);
        for (Issue issue : projeto.getIssue()) {
            issueLabelDao.bulkSave(issue.getLabels());
        }
        projectDao.save(projeto);
    }//GEN-LAST:event_btnIssueActionPerformed

    private void btnArquivosCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivosCommitActionPerformed
        autenticate();
        Project projeto = ExtracaoRepository.extractRepository(client, repo);
        List<Commit> commits = projectDao.getById(projeto.getId()).getCommits();
        List<Commit> commitsFile = ExtracaoCommit.extract(client, repo, commits);
//        commitDao.bulkSave(commitsFile);
    }//GEN-LAST:event_btnArquivosCommitActionPerformed

    private void btnIssueComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueComentariosActionPerformed
        IssueDao issue = new IssueDao();
        List<Issue> issues = issue.findAll(Issue.class);
    }//GEN-LAST:event_btnIssueComentariosActionPerformed

    private void btnPullRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPullRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPullRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtractView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtractView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtractView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtractView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtractView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nome;
    private javax.swing.JButton btnArquivosCommit;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton btnIssueComentarios;
    private javax.swing.JButton btnPullRequest;
    private javax.swing.JTextField inputNomeProjeto;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JTextField inputUsuarioProjeto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
